version: '3.5'
networks:
  basic:
    driver:
      bridge
  microservices:
    external: true
volumes:
  db:
    driver: local
services:
  nginx:
    networks:
      - basic
      - microservices
    image: nginx:1.13.6
    ports:
      - "9191:80"
    volumes:
      - .:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm
  fpm:
    container_name: rapido-api
    networks:
      - basic
    volumes:
      - .:/var/www/html
    build:
      context: .
      dockerfile: ./docker/Dockerfile-fpm
    links:
      - db
      - redis
  db:
    networks:
      - basic
    image: mysql
    ports:
      - "3316:3306"
    command: --default-authentication-plugin=mysql_native_password
    links:
      - adminer
    environment:
      - MYSQL_DATABASE=rapido_db
      - MYSQL_USER=rapido_db_user
      - MYSQL_PASSWORD=r@p!d0
      - MYSQL_ROOT_PASSWORD=r@p!d0
    volumes:
      #- "./data:/docker-entrypoint-initdb.d"
      - ./data/mysql:/var/lib/mysql
  redis:
    networks:
      - basic
    image: redis:6.2.6
    ports:
      - "6000:6379"
    volumes:
      - ./data/redis:/data
  adminer:
    networks:
      - basic
    image: adminer
    ports:
      - "5555:8080"
