FROM php:8.1-fpm

RUN apt-get update
RUN apt-get install -y libpq-dev libpng-dev curl unzip zip git jq supervisor
RUN docker-php-ext-install mysqli && docker-php-ext-install pdo && docker-php-ext-install pdo_mysql
#RUN docker-php-ext-install pdo_pgsql && docker-php-ext-enable pdo_pgsql
#RUN apt-get install -y git supervisor
RUN apt-get install libxrender1
RUN apt-get install -y libfontconfig1
#RUN apt-get install -y libxml2-dev unzip && docker-php-ext-install soap && docker-php-ext-enable soap
RUN apt-get install -y libxml2-dev && docker-php-ext-install soap && docker-php-ext-enable soap

#install redis
RUN pecl install -o -f redis \
&&  rm -rf /tmp/pear \
&&  docker-php-ext-enable redis

# GD
RUN apt-get update
RUN apt-get install -y libwebp-dev libjpeg62-turbo-dev libpng-dev libxpm-dev \
    libfreetype6-dev

RUN docker-php-ext-install gd

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.2.2
